function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
	"Snape's original patronus: __________.",
	"I'm allergic to __________. I'm a Hufflepuff!	",
	"Next from JK Rowling: Harry Potter and __________.",
	"The Weird Sisters' next hit: __________.",
	"What do the Ravenclaws keep in their towers?	",
	"The answer to the last Ravenclaw password question.",
	"Where do the Hufflepuffs keep their food?	",
	"All the house elves want is to be paid in __________.",
	"Son, you were named after __________ and __________.",
	"I looked in the Mirror of Erised and saw __________.",
	"Hermione Granger's latest cause: __________.",
	"__________'s patronus: __________.",
	"__________'s boggart: __________.",
	"My OTP: __________ and __________.",
	"__________ should be canon.",
	"What was the diadem's original hiding place?	",
	"Exclusive from The Daily Prophet: The Dangers of ________.",
	"Gilderoy Lockhart's next book: ________.",
	"Crumple-Horned Snorkacks are so last year. Now it's all about __________.",
	"The last horcrux can be found in __________.",
	"You might belong in Gryffindor, where dwell ________.",
	"For Ravenclaw, __________ would always be the best.",
	"You might belong in Hufflepuff, where they are __________.",
	"Albus Dumbledore's best decision includes __________.",
	"Those cunning folks use any means to achieve __________.",
	"Ten points to Gryffindor for __________!	",
	"Fifty points from Gryffindor for __________.",
	"Lord Voldemort's secret plan: __________.",
	"How the 234th Quidditch World Cup was won.",
	"The real cause of You Know Who's demise.",
	"__________: A Forbidden Journey.",
	"__________: Nineteen Years Later.",
	"Did you hear? Harry Potter just vanquished __________.",
	"What the first war was fought for.",
	"If they won't close Hogwarts for __________, then they won't close it for __________.",
	"Why isn't Uncle Charlie married?	",
	"Why did I never get my Hogwarts letter?	",
	"How did we end up in the Forbidden Forest in the dead of the night again?	",
	"Why are we in the Shrieking Shack?	",
	"What's in the Leaky Cauldron special?	",
	"______ is my favourite Bertie Botts' Every Flavour Bean flavour.	"
  ];
}

function white() {
  return [
   	"Snape, Snape, Severus Snape.",
	"The Amazon reviews for the vibrating Harry Potter Nimbus 2000 broomstick.",
	"Diagon Alley after dark.",
	"A Cauldron Full of Hot, Strong Love.",
	"Accidentally polyjuicing yourself into a cat furry.",
	"Waiting for your Hogwarts acceptance letter.",
	"That time everyone thought you were the Heir of Slytherin.",
	"Polyjuice brothels.",
	"An amazingly well-trained phoenix.",
	"Dobby's sock.",
	"The mysterious ticking noise.",
	"Dead parents.",
	"Harry Potter erotica.",
	"The Scarf of Sexual Preference.",
	"Spelling Lucius Luscious.",
	"Pet names for the Dark Lord.",
	"Slytherin dungeon orgies.",
	"The Sorting Hat on Muggle drugs.",
	"Babbity Rabbity's Cackling Stump.",
	"Mistaking Hufflepuff for Pokemon.",
	"Snogging your best friend's sister.",
	"Getting cable in the Room of Requirement.",
	"Abusing time turners for fun and profit.",
	"Twincest.",
	"Draco Malfoy in leather pants.",
	"Squib rights.",
	"Gilderoy Lockhart.",
	"Rita Skeeter.",
	"Dolores Umbridge's favorite pussy.",
	"Sucking on sugar quills.",
	"Hufflepuffs.",
	"Prejudice against Slytherins.",
	"Bartending in the dark.",
	"Hermione Granger's buck teeth.",
	"Milking a provoked hippogriff attack for all it's worth.",
	"Mrs. Zabini's husbands.",
	"DADA professors.",
	"The epilogue.",
	"Illegal Animagus transformations.",
	"Uncomfortably attractive centaurs.",
	"Grumpy Hufflepuffs.",
	"Winning the House Cup on a last-minute technicality.",
	"Not listening to Hermione.",
	"Camping and calling it hunting for horcruxes.",
	"Stealing a House mascot for fun and profit.",
	"Nagini's balls.",
	"Aberforth Dumbledore's goat incident.",
	"Getting drunk on butterbeer.",
	"Waking up with the Dark Mark on your arse.",
	"Commentating Quidditch matches with Loony Lovegood.",
	"A Slug Club membership.",
	"Sneaking into the Prefect's bathroom.",
	"The real reason they call her Moaning Myrtle.",
	"The Weasley family reunion.",
	"Blaming the nanny for your sock puppet accounts.",
	"Speaking Mermish.",
	"Extended playtime with the Giant Squid.",
	"Culturally insensitive Quidditch team mascots.",
	"Dementor kisses.",
	"Exploding Quaffles.",
	"Swallowing snitches.",
	"Madam Rosmerta's secret recipe.",
	"Swishing and flicking.",
	"Muggle tipping.",
	"Excessive blagging.",
	"Surprise goblin uprisings.",
	"Making Remus sing Howling at the Moon.",
	"The Room of Requirement.",
	"Ravenclaws.",
	"Slytherins.",
	"Gryffindors.",
	"Intoxicated house elves.",
	"Pureblood preppies.",
	"Weasley sweaters.",
	"Moody's Mad Eye.",
	"Part-Veela heritage.",
	"Cedric Diggory's tragic afterlife as a sparkly vampire.",
	"Forgetting the epilogue ever happened.",
	"Draco Malfoy's receding hairline.",
	"Hugging like brothers.",
	"Lucius Malfoy's pimp cane.",
	"Harry Potter's chest monster.",
	"Hagrid's latest pet.",
	"Illegally acquired Felix Felicis.",
	"Albus Dumbledore's good intentions.",
	"Harmony shippers.",
	"Dursley family values.",
	"Doing the hippogriff.",
	"The Shoebox Project.",
	"Professor McGonagall.",
	"Filius Flitwick.",
	"Poppy Pomfrey.",
	"Albus Severus Potter.",
	"Argus Filch.",
	"Winky.",
	"Kreacher.",
	"Goats.",
  ];
}

exports.getDeck = getDeck;
